CREATE TABLE Rzeczoznawca (
	Id INT IDENTITY PRIMARY KEY,
	Nr INT,
	Imie VARCHAR(50),
	Nazwisko VARCHAR(50),
	Mail VARCHAR(50));

CREATE TABLE Cennik (
	Id INT IDENTITY PRIMARY KEY,
	TYP VARCHAR(70),
	Cena DECIMAL(10,2));

CREATE TABLE Zlecenie (
	Id INT IDENTITY PRIMARY KEY,
	IMIE VARCHAR(50),
	NAZWISKO VARCHAR(50),
	MAIL VARCHAR(50),
	Tel INT,
	DataZlecenia DATE,
	Miasto VARCHAR(50),
	Adres VARCHAR(100),
	IdRzeczoznawca INT,
	IdCennik INT);

ALTER TABLE Zlecenie
   ADD CONSTRAINT FK_ZLECENIE_Rzeczoznawca FOREIGN KEY (IdRzeczoznawca)
      REFERENCES Rzeczoznawca (Id)
      ON DELETE CASCADE
      ON UPDATE CASCADE;

ALTER TABLE Zlecenie
   ADD CONSTRAINT FK_ZLECENIE_CENNIK FOREIGN KEY (IdCennik)
      REFERENCES Cennik (Id)
      ON DELETE CASCADE
      ON UPDATE CASCADE;